# Generated by Django 2.2.1 on 2019-06-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pedidos', '0003_auto_20190604_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='cod_produto',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
