# Generated by Django 2.2.1 on 2019-06-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pedidos', '0005_auto_20190605_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='cod_produto',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
