# Generated by Django 2.2.1 on 2019-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pedidos', '0006_auto_20190605_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='quantidade',
            field=models.SmallIntegerField(default=0),
        ),
    ]
