# Generated by Django 2.2.1 on 2019-06-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pedidos', '0007_auto_20190605_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cod_mesa',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
