# Generated by Django 2.2.1 on 2019-06-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pedidos', '0008_pedido_cod_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pronto',
        ),
    ]
